apiVersion: v1
kind: Service
metadata:
  name: k8s-github-runner-controller-metrics
  namespace: github-runner
spec:
  selector:
    app.kubernetes.io/name: gha-rs-controller
    app.kubernetes.io/component: controller-manager
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
