apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-runner-app-credentials
  namespace: github-runner
  annotations:
    force-sync: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: github-runner-app-credentials
    creationPolicy: Owner
  data:
    - secretKey: github_app_id
      remoteRef:
        key: homelab/k8s-github-runner/github-app-id
        property: value
    - secretKey: github_app_installation_id
      remoteRef:
        key: homelab/k8s-github-runner/github-app-installation-id
        property: value
    - secretKey: github_app_private_key
      remoteRef:
        key: homelab/k8s-github-runner/github-app-private-key
        property: value
